name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    # define a runner/env
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, World!"
      - name: Print goodbye
        run: echo "Done - bye!"
